---
title: "En blog om svensk fäktstatistik"
listing:
  contents: posts
  sort: "date desc"
  type: default
  categories: true
  sort-ui: false
  filter-ui: false
page-layout: full
title-block-banner: true
---

I FFFs verksamhetsberättelse ingår årligen ett avsnitt med tävlingsstatistik. De senaste åren har detta avsnitt ökat i omfattning och för verskamhetsåret 2023 innefattar detta avsnitt samtliga uppgifter från en stor mängd svenska tävlingar. Att samlar in dessa uppgifter är en ganska stor arbetsuppgift, men när data väl finns på plats är det relativt enkelt att sammanställa och analysera dataunderlaget.

När nu ändå informationen finns tillgänglig så är det inte en så stor ansträngning att också göra informationen tillgänglig till en vidare grupp än endast FFFare, vilka var den ursprungliga målgruppen.

Jag medger att allt detta är svårt nördigt och jag inser också att intresset av detta sannolikt är näst intill obefintligt. Om det trots allt finns någon mänsklig varelse som delar mitt skadliga intressa av denna typ av statistik är ni välkomna att ta del av innehållet.
